export const types = Object.freeze({
  USER_START_REQUEST: 'USER_START_REQUEST',
  USER_STOP_REQUEST: 'USER_STOP_REQUEST',

  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_REGISTER_ASYNC: 'USER_REGISTER_ASYNC',

  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGIN_ASYNC: 'USER_LOGIN_ASYNC',

  USER_GET_USER_FAIL: 'USER_GET_USER_FAIL',
  USER_GET_USER_ASYNC: 'USER_GET_USER_ASYNC',

  USER_LOGOUT_FAIL: 'USER_LOGOUT_FAIL',
  USER_LOGOUT_ASYNC: 'USER_LOGOUT_ASYNC',

  USER_UPDATE_USER_FAIL: 'USER_UPDATE_USER_FAIL',
  USER_UPDATE_USER_ASYNC: 'USER_UPDATE_USER_ASYNC',

  USER_PROFILE_FILL: 'USER_PROFILE_FILL'
});
