export const types = Object.freeze({
  TRACKER_START_REQUEST: 'TRACKER_START_REQUEST',
  TRACKER_STOP_REQUEST: 'TRACKER_STOP_REQUEST',
  TRACKER_SCORE_FILL: 'TRACKER_SCORE_FILL',
  TRACKER_RECORD_FILL: 'TRACKER_RECORD_FILL',

  TRACKER_GET_RECORD_FAIL: 'TRACKER_GET_RECORD_FAIL',
  TRACKER_GET_RECORD_ASYNC: 'TRACKER_GET_RECORD_ASYNC',

  TRACKER_CREATE_RECORD_FAIL: 'TRACKER_CREATE_RECORD_FAIL',
  TRACKER_CREATE_RECORD_ASYNC: 'TRACKER_CREATE_RECORD_ASYNC',

  TRACKER_UPDATE_RECORD_FAIL: 'TRACKER_UPDATE_RECORD_FAIL',
  TRACKER_UPDATE_RECORD_ASYNC: 'TRACKER_UPDATE_RECORD_ASYNC',

  TRACKER_GET_SCORE_FAIL: 'TRACKER_GET_SCORE_FAIL',
  TRACKER_GET_SCORE_ASYNC: 'TRACKER_GET_SCORE_ASYNC',

  TRACKER_RESET_SCORE_FAIL: 'TRACKER_RESET_SCORE_FAIL',
  TRACKER_RESET_SCORE_ASYNC: 'TRACKER_RESET_SCORE_ASYNC',
});
